/*
 * Generated by gdbus-codegen 2.48.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __XFCONF_GDBUS_BINDINGS_H__
#define __XFCONF_GDBUS_BINDINGS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.xfce.Xfconf */

#define XFCONF_TYPE_CLIENT (xfconf_client_get_type ())
#define XFCONF_CLIENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), XFCONF_TYPE_CLIENT, XfconfClient))
#define XFCONF_IS_CLIENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), XFCONF_TYPE_CLIENT))
#define XFCONF_CLIENT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), XFCONF_TYPE_CLIENT, XfconfClientIface))

struct _XfconfClient;
typedef struct _XfconfClient XfconfClient;
typedef struct _XfconfClientIface XfconfClientIface;

struct _XfconfClientIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_all_properties) (
    XfconfClient *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_channel,
    const gchar *arg_property_base);

  gboolean (*handle_get_property) (
    XfconfClient *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_channel,
    const gchar *arg_property);

  gboolean (*handle_is_property_locked) (
    XfconfClient *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_channel,
    const gchar *arg_property);

  gboolean (*handle_list_channels) (
    XfconfClient *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_property_exists) (
    XfconfClient *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_channel,
    const gchar *arg_property);

  gboolean (*handle_reset_property) (
    XfconfClient *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_channel,
    const gchar *arg_property,
    gboolean arg_recursive);

  gboolean (*handle_set_property) (
    XfconfClient *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_channel,
    const gchar *arg_property,
    GVariant *arg_value);

  void (*property_changed) (
    XfconfClient *object,
    const gchar *arg_channel,
    const gchar *arg_property,
    GVariant *arg_value);

  void (*property_removed) (
    XfconfClient *object,
    const gchar *arg_channel,
    const gchar *arg_property);

};

GType xfconf_client_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *xfconf_client_interface_info (void);
guint xfconf_client_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void xfconf_client_complete_set_property (
    XfconfClient *object,
    GDBusMethodInvocation *invocation);

void xfconf_client_complete_get_property (
    XfconfClient *object,
    GDBusMethodInvocation *invocation,
    GVariant *value);

void xfconf_client_complete_get_all_properties (
    XfconfClient *object,
    GDBusMethodInvocation *invocation,
    GVariant *properties);

void xfconf_client_complete_property_exists (
    XfconfClient *object,
    GDBusMethodInvocation *invocation,
    gboolean exists);

void xfconf_client_complete_reset_property (
    XfconfClient *object,
    GDBusMethodInvocation *invocation);

void xfconf_client_complete_list_channels (
    XfconfClient *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *channels);

void xfconf_client_complete_is_property_locked (
    XfconfClient *object,
    GDBusMethodInvocation *invocation,
    gboolean locked);



/* D-Bus signal emissions functions: */
void xfconf_client_emit_property_changed (
    XfconfClient *object,
    const gchar *arg_channel,
    const gchar *arg_property,
    GVariant *arg_value);

void xfconf_client_emit_property_removed (
    XfconfClient *object,
    const gchar *arg_channel,
    const gchar *arg_property);



/* D-Bus method calls: */
void xfconf_client_call_set_property (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property,
    GVariant *arg_value,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean xfconf_client_call_set_property_finish (
    XfconfClient *proxy,
    GAsyncResult *res,
    GError **error);

gboolean xfconf_client_call_set_property_sync (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property,
    GVariant *arg_value,
    GCancellable *cancellable,
    GError **error);

void xfconf_client_call_get_property (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean xfconf_client_call_get_property_finish (
    XfconfClient *proxy,
    GVariant **out_value,
    GAsyncResult *res,
    GError **error);

gboolean xfconf_client_call_get_property_sync (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property,
    GVariant **out_value,
    GCancellable *cancellable,
    GError **error);

void xfconf_client_call_get_all_properties (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property_base,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean xfconf_client_call_get_all_properties_finish (
    XfconfClient *proxy,
    GVariant **out_properties,
    GAsyncResult *res,
    GError **error);

gboolean xfconf_client_call_get_all_properties_sync (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property_base,
    GVariant **out_properties,
    GCancellable *cancellable,
    GError **error);

void xfconf_client_call_property_exists (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean xfconf_client_call_property_exists_finish (
    XfconfClient *proxy,
    gboolean *out_exists,
    GAsyncResult *res,
    GError **error);

gboolean xfconf_client_call_property_exists_sync (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property,
    gboolean *out_exists,
    GCancellable *cancellable,
    GError **error);

void xfconf_client_call_reset_property (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property,
    gboolean arg_recursive,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean xfconf_client_call_reset_property_finish (
    XfconfClient *proxy,
    GAsyncResult *res,
    GError **error);

gboolean xfconf_client_call_reset_property_sync (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property,
    gboolean arg_recursive,
    GCancellable *cancellable,
    GError **error);

void xfconf_client_call_list_channels (
    XfconfClient *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean xfconf_client_call_list_channels_finish (
    XfconfClient *proxy,
    gchar ***out_channels,
    GAsyncResult *res,
    GError **error);

gboolean xfconf_client_call_list_channels_sync (
    XfconfClient *proxy,
    gchar ***out_channels,
    GCancellable *cancellable,
    GError **error);

void xfconf_client_call_is_property_locked (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean xfconf_client_call_is_property_locked_finish (
    XfconfClient *proxy,
    gboolean *out_locked,
    GAsyncResult *res,
    GError **error);

gboolean xfconf_client_call_is_property_locked_sync (
    XfconfClient *proxy,
    const gchar *arg_channel,
    const gchar *arg_property,
    gboolean *out_locked,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define XFCONF_TYPE_CLIENT_PROXY (xfconf_client_proxy_get_type ())
#define XFCONF_CLIENT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), XFCONF_TYPE_CLIENT_PROXY, XfconfClientProxy))
#define XFCONF_CLIENT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), XFCONF_TYPE_CLIENT_PROXY, XfconfClientProxyClass))
#define XFCONF_CLIENT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), XFCONF_TYPE_CLIENT_PROXY, XfconfClientProxyClass))
#define XFCONF_IS_CLIENT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), XFCONF_TYPE_CLIENT_PROXY))
#define XFCONF_IS_CLIENT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), XFCONF_TYPE_CLIENT_PROXY))

typedef struct _XfconfClientProxy XfconfClientProxy;
typedef struct _XfconfClientProxyClass XfconfClientProxyClass;
typedef struct _XfconfClientProxyPrivate XfconfClientProxyPrivate;

struct _XfconfClientProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  XfconfClientProxyPrivate *priv;
};

struct _XfconfClientProxyClass
{
  GDBusProxyClass parent_class;
};

GType xfconf_client_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XfconfClientProxy, g_object_unref)
#endif

void xfconf_client_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
XfconfClient *xfconf_client_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
XfconfClient *xfconf_client_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void xfconf_client_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
XfconfClient *xfconf_client_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
XfconfClient *xfconf_client_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define XFCONF_TYPE_CLIENT_SKELETON (xfconf_client_skeleton_get_type ())
#define XFCONF_CLIENT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), XFCONF_TYPE_CLIENT_SKELETON, XfconfClientSkeleton))
#define XFCONF_CLIENT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), XFCONF_TYPE_CLIENT_SKELETON, XfconfClientSkeletonClass))
#define XFCONF_CLIENT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), XFCONF_TYPE_CLIENT_SKELETON, XfconfClientSkeletonClass))
#define XFCONF_IS_CLIENT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), XFCONF_TYPE_CLIENT_SKELETON))
#define XFCONF_IS_CLIENT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), XFCONF_TYPE_CLIENT_SKELETON))

typedef struct _XfconfClientSkeleton XfconfClientSkeleton;
typedef struct _XfconfClientSkeletonClass XfconfClientSkeletonClass;
typedef struct _XfconfClientSkeletonPrivate XfconfClientSkeletonPrivate;

struct _XfconfClientSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  XfconfClientSkeletonPrivate *priv;
};

struct _XfconfClientSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType xfconf_client_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XfconfClientSkeleton, g_object_unref)
#endif

XfconfClient *xfconf_client_skeleton_new (void);


G_END_DECLS

#endif /* __XFCONF_GDBUS_BINDINGS_H__ */
